import type {Metadata} from "next";
import {Inter} from "next/font/google";
import React from "react";
import SiteHeader from "@/components/site-header";
import SiteFooter from "@/components/site-footer";
import "./globals.css";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Layers - Landing Page",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
    <body className={`${inter.className} antialiased`}>
    <div className="flex flex-col min-h-screen">
      <SiteHeader/>
      {children}
      <SiteFooter/>
    </div>
    </body>
    </html>
  )
}
