import type {Metadata} from "next";
import {Inter} from "next/font/google";
import React from "react";
import SiteHeader from "@/components/site-header";
import SiteFooter from "@/components/site-footer";
import "./globals.css";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Design Tool Landing Page",
  description: "Generated by create next app",
  openGraph: {
    type: "website",
    title: "Design Tool Landing Page",
    description: "A sleek, dark-mode landing page built with Next.js 15, Tailwind CSS, Framer Motion & Shadcn UI. Built by Moussa.",
    images: [
      {
        url: "https://design-tool-lp.vercel.app/preview.png",
        width: 1200,
        height: 630,
        alt: "Design Tool Landing Page",
        type: "image/png",
      },
    ],
  }
};

export default function RootLayout({children}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
    <body className={`${inter.className} antialiased`}>
    <div className="flex flex-col min-h-screen">
      <SiteHeader/>
      {children}
      <SiteFooter/>
    </div>
    </body>
    </html>
  )
}
